spring:
  datasource:
    url: jdbc:mysql://root:SnAHsqkGwLpzQMgUNKbdKLJsetAPWnFQ@junction.proxy.rlwy.net:37963/railway
    username: root
    password: SnAHsqkGwLpzQMgUNKbdKLJsetAPWnFQ
  jpa:
    hibernate:
      ddl-auto: create-drop
