spring:
  datasource:
    url: jdbc:mysql://root:PhulOnNLXzmUKVKwNCxucPLTZjcpfAWx@autorack.proxy.rlwy.net:54713/railway
    username: root
    password: PhulOnNLXzmUKVKwNCxucPLTZjcpfAWx
  jpa:
    hibernate:
      ddl-auto: create-drop