spring:
  datasource:
    url: jdbc:mysql://root:mEbeTyUOvURknbzPJWBBIxBNeHLmBEuL@autorack.proxy.rlwy.net:52433/railway
    username: root
    password: mEbeTyUOvURknbzPJWBBIxBNeHLmBEuL
  jpa:
    hibernate:
      ddl-auto: create-drop