spring:
  datasource:
    url: jdbc:mysql://root:mEbeTyUOvURknbzPJWBBIxBNeHLmBEuL@mysql.railway.internal:3306/railway
    username: root
    password: mEbeTyUOvURknbzPJWBBIxBNeHLmBEuL
  jpa:
    hibernate:
      ddl-auto: create-drop